#+title: Platica [[https://nancynsalazar.tech/][Nancy Salazar]]
#+author: Leonardo Noriega

* ¿Quién es Nancy Salazar?
Nancy Salazar es una experta en tecnologías de la información.
Fundadora de tekis.services
Ingeniera en TI con maestría en Gestión de TI.
Líder de Mentores e Instructora de Programación Web con [[https://tecnolochicas.mx/][Tecnolochicas]] y profesora en [[https://platzi.com/][Platzi]] TopVoice de Linkedin.
Si te interesa saber más de Nancy Salazar:
- [[https://www.linkedin.com/in/nancynsalazar/][LinkedIn]]
- [[https://platzi.com/profes/NancyNSalazar/][Platzi]]
** Capacitarte por tu cuenta, ser autodidacta
- Plataformas online.
- Bootcamps.
- Dar talleres a personas que estan un nivel antes que tú.
- Leer libros, suscribirse a newsletters, escuchar podcasts, conferencias, artículos, blogs, todos relacionados con el tema que queremos dominar
** Trabaja en tu marca personal
Tener presencia off y online, crear contenido que queremos transmitir o sea dar una buena primera impresión; hay un curso en Platzi para crear tu marca profesional

** Crea redes de contacto sin temor
Es importante seguir en redes o mandarles solicitud en LinkedIn ([[https://www.linkedin.com/in/leo-noriega][Aquí te dejo el mío)]] nos permite seguir conectando con esa personas y poder generar nuevas oportunidades.
Mas alla de tus habilidades tecnicas o core skills, los contactos siempre ayudan mucho, siempre contactar con gente a la que le sumemos valor y ellos a nosotros.

** Únete a la comunidades tech
Desarrolla habilidades profesionales que seguramente en un futuro te ayudarán en el ámbito profesional.
Conecta con los líderes de dichas comunidades.
Ofrecete como voluntario, hazte notar, colabora sin buscar un interés monetario.
Comparte tu conocimiento y aprende de las demás personas.
