#+title: Platica [[https://nancynsalazar.tech/][Nancy Salazar]]
#+author: Leonardo Noriega

* Quien es Nancy Salazar?
Nancy Salazar es una experta en tecnologias de la informacion.
Founder de tekis.services
Ingeniera en TI con maestria en Gestión de TI.
Líder de Mentores e Instructora de Programación Web con [[https://tecnolochicas.mx/][Tecnolochicas]] y profesora en [[https://platzi.com/][Platzi]] TopVoice de Linkedin.
Si te interesa saber mas de Nancy Salazar:
- [[https://www.linkedin.com/in/nancynsalazar/][LinkedIn]]
- [[https://platzi.com/profes/NancyNSalazar/][Platzi]]
* Capacitarte por tu cuenta, ser autodidacta
- Plataformas onlines
- Bootcamps
- Dar talleres a personas que estan un nivel antes que tu
- Leer libros, suscribirse a newsletters, escuchar podcast, conferencias, articulos, blogs, relacionados al tema que queremos dominar
* Trabaja en tu marca personal
Tener presencial off y online, crear contenido que queremos transmitir o sea dar una buena primera impresion, hay un curso en Platzi de crear tu marca profesional
* Crea redes de contacto sin temor
Es importante seguir en redes o mandarles solicitud en [[www.linkedin.com/in/leo-noriega][LinkedIn]] (mas profesional) nos permite seguir conectando con esa personas y poder generar nuevas oportunidades.
Mas alla de tus habilidades tecnicas o core skills, los contactos siempre ayudan mucho, siempre contactar con gente a la que le sumemos valor y ellos a nosotros.
* Unirse a la comunidades tech
Desarrollas habilidades profesionales que seguramente en un futuro te ayuden en el ambito profesional.
Conecta con los lideres de dichas comunidades.
Ofrecete como voluntario, hazte notar, colabora sin buscar un interes monetario.
Comparte tu conocimiento y aprende de las demas personas.
